//
// Created by Maelan Leost on 02/03/2023.
//

#ifndef PROJET_SYNTHÈSE_LEOST_MAELAN_THUILLIER_COLIN_CERCLE_H
#define PROJET_SYNTHÈSE_LEOST_MAELAN_THUILLIER_COLIN_CERCLE_H

#include "Forme.h"

class Cercle : public Forme
{

};


#endif //PROJET_SYNTHÈSE_LEOST_MAELAN_THUILLIER_COLIN_CERCLE_H
