//
// Created by Maelan Leost on 02/03/2023.
//

#ifndef PROJET_SYNTHÈSE_LEOST_MAELAN_THUILLIER_COLIN_FORME_H
#define PROJET_SYNTHÈSE_LEOST_MAELAN_THUILLIER_COLIN_FORME_H


class Forme {

};


#endif //PROJET_SYNTHÈSE_LEOST_MAELAN_THUILLIER_COLIN_FORME_H
