//
// Created by Maelan Leost on 02/03/2023.
//

#ifndef PROJET_SYNTHÈSE_LEOST_MAELAN_THUILLIER_COLIN_POLYGONE_H
#define PROJET_SYNTHÈSE_LEOST_MAELAN_THUILLIER_COLIN_POLYGONE_H

#include "Forme.h"

class Polygone: public Forme {

};


#endif //PROJET_SYNTHÈSE_LEOST_MAELAN_THUILLIER_COLIN_POLYGONE_H
